In [1]:
import numpy as np, pandas as pd

In [16]:
file = '../datasets/Products.csv'
df = pd.read_csv(file, index_col='Product ID')
df.head(10)

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country
Product ID,,,,,,,,,,,,,
101,Monitor,Accessories,1156,482,29,Brand C,0.21,NaN,2020-07-20,2.0,NaN,Best in class,India
102,Headphones,Clothing,289,305,45,Brand E,0.06,3.0,2022-01-16,1.0,Supplier B,Best in class,China
103,Charger,Home Appliances,4942,197,106,Brand E,0.07,NaN,2024-11-11,2.0,Supplier C,Top selling,China
104,Laptop,Clothing,1359,328,259,Brand E,0.13,NaN,2022-12-18,NaN,NaN,Affordable price,India
105,Camera,Electronics,4382,204,166,Brand E,0.34,NaN,2024-08-26,3.0,Supplier B,Best in class,China
106,Laptop,Clothing,3038,182,213,Brand B,0.13,NaN,2020-04-22,NaN,Supplier A,Top selling,Germany
107,Charger,Accessories,963,324,118,Brand A,0.16,4.0,2022-07-26,2.0,Supplier B,Good quality product,USA
108,Charger,Electronics,4092,388,119,Brand A,0.05,NaN,2021-12-30,2.0,Supplier C,NaN,China
109,Mouse,Home Appliances,482,400,11,Brand D,0.16,5.0,2024-08-23,NaN,NaN,NaN,NaN
110,Charger,Clothing,2344,292,254,Brand B,0.12,5.0,2023-03-10,5.0,Supplier B,Good quality product,USA

In [17]:
df.shape

(400, 13)

In [18]:
df.columns

Index(['Product Name', 'Category', 'Price', 'Stock', 'Sales', 'Brand',
       'Discount', 'Rating', 'Launch Date', 'Warranty Period (Years)',
       'Supplier', 'Product Description', 'Manufacture Country'],
      dtype='object')

In [19]:
df.dtypes

Product Name                object
Category                    object
Price                        int64
Stock                        int64
Sales                        int64
Brand                       object
Discount                   float64
Rating                     float64
Launch Date                 object
Warranty Period (Years)    float64
Supplier                    object
Product Description         object
Manufacture Country         object
dtype: object

In [26]:
df.isna().sum()

Product Name                0
Category                    0
Price                       0
Stock                       0
Sales                       0
Brand                       0
Discount                    0
Rating                     71
Launch Date                 0
Warranty Period (Years)    95
Supplier                   96
Product Description        76
Manufacture Country        80
dtype: int64

In [35]:
df['Rating'].fillna(df['Rating'].mean(), inplace=True)

In [36]:
df

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country
Product ID,,,,,,,,,,,,,
101,Monitor,Accessories,1156,482,29,Brand C,0.21,2.993921,2020-07-20,2.0,NaN,Best in class,India
102,Headphones,Clothing,289,305,45,Brand E,0.06,3.000000,2022-01-16,1.0,Supplier B,Best in class,China
103,Charger,Home Appliances,4942,197,106,Brand E,0.07,2.993921,2024-11-11,2.0,Supplier C,Top selling,China
104,Laptop,Clothing,1359,328,259,Brand E,0.13,2.993921,2022-12-18,NaN,NaN,Affordable price,India
105,Camera,Electronics,4382,204,166,Brand E,0.34,2.993921,2024-08-26,3.0,Supplier B,Best in class,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Tablet,Accessories,829,285,197,Brand E,0.22,5.000000,2020-03-04,5.0,NaN,Good quality product,India
497,Keyboard,Home Appliances,4762,244,149,Brand E,0.34,2.000000,2024-07-01,2.0,NaN,Top selling,China
498,Monitor,Accessories,478,413,88,Brand C,0.30,4.000000,2023-04-13,3.0,Supplier A,NaN,China
499,Charger,Furniture,3005,302,226,Brand E,0.14,2.000000,2020-06-15,2.0,Supplier B,NaN,India
500,Monitor,Electronics,3403,255,97,Brand B,0.18,3.000000,2021-01-13,1.0,Supplier B,Top selling,Germany

In [40]:
df.loc[(df['Price'] == max(df['Price'])), ['Product Name', 'Price']]
# max(df['Price'])

           Product Name  Price
Product ID
207             Monitor   4999

In [42]:
avgHigh = (df['Price'] > df['Price'].mean())
df.loc[avgHigh]

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country
Product ID,,,,,,,,,,,,,
103,Charger,Home Appliances,4942,197,106,Brand E,0.07,2.993921,2024-11-11,2.0,Supplier C,Top selling,China
105,Camera,Electronics,4382,204,166,Brand E,0.34,2.993921,2024-08-26,3.0,Supplier B,Best in class,China
106,Laptop,Clothing,3038,182,213,Brand B,0.13,2.993921,2020-04-22,NaN,Supplier A,Top selling,Germany
108,Charger,Electronics,4092,388,119,Brand A,0.05,2.993921,2021-12-30,2.0,Supplier C,NaN,China
111,Keyboard,Home Appliances,4350,408,241,Brand C,0.24,2.000000,2022-10-07,1.0,Supplier B,Affordable price,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,Keyboard,Home Appliances,4314,66,8,Brand E,0.20,3.000000,2020-03-14,2.0,Supplier C,Good quality product,USA
495,Charger,Furniture,2980,386,137,Brand B,0.08,2.993921,2022-08-15,3.0,Supplier C,Top selling,India
497,Keyboard,Home Appliances,4762,244,149,Brand E,0.34,2.000000,2024-07-01,2.0,NaN,Top selling,China
499,Charger,Furniture,3005,302,226,Brand E,0.14,2.000000,2020-06-15,2.0,Supplier B,NaN,India
500,Monitor,Electronics,3403,255,97,Brand B,0.18,3.000000,2021-01-13,1.0,Supplier B,Top selling,Germany

In [ ]:
avgPrices = df.groupby('Category')['Price'].mean()

In [68]:
expensiveCategory = avgPrices.idxmax()
itsAvgValue = max(avgPrices)
print(expensiveCategory, '--->', itsAvgValue)

Furniture ---> 2825.864864864865

In [77]:
stockVal = df.groupby('Category')['Stock'].count()
stockVal

Category
Accessories        78
Clothing           79
Electronics        79
Furniture          74
Home Appliances    90
Name: Stock, dtype: int64

In [78]:
avgPrices = df.loc[df.groupby('Category')['Price'].idxmax()]
avgPrices

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country
Product ID,,,,,,,,,,,,,
175,Smartwatch,Accessories,4964,475,57,Brand C,0.15,1.0,2024-09-15,3.0,Supplier A,NaN,NaN
153,Camera,Clothing,4959,147,104,Brand B,0.13,3.0,2021-04-03,NaN,NaN,Top selling,USA
140,Keyboard,Electronics,4833,115,156,Brand A,0.11,1.0,2023-11-18,NaN,Supplier B,Affordable price,China
185,Monitor,Furniture,4945,47,297,Brand D,0.33,1.0,2021-08-07,1.0,NaN,Best in class,USA
207,Monitor,Home Appliances,4999,311,149,Brand A,0.29,3.0,2024-05-01,2.0,NaN,Affordable price,Germany

In [82]:
category_brand_val = df.loc[df.groupby(['Category', 'Brand'])['Price'].idxmax()]
category_brand_val

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country
Product ID,,,,,,,,,,,,,
272,Charger,Accessories,4936,349,290,Brand A,0.26,2.000000,2022-02-14,1.0,Supplier B,Best in class,India
403,Keyboard,Accessories,4529,361,162,Brand B,0.34,1.000000,2021-11-30,1.0,Supplier B,NaN,Germany
175,Smartwatch,Accessories,4964,475,57,Brand C,0.15,1.000000,2024-09-15,3.0,Supplier A,NaN,NaN
395,Charger,Accessories,4678,495,145,Brand D,0.28,5.000000,2023-04-04,5.0,NaN,Top selling,Germany
412,Mouse,Accessories,4795,324,97,Brand E,0.10,1.000000,2024-12-01,2.0,Supplier A,Affordable price,NaN
330,Tablet,Clothing,4549,299,249,Brand A,0.15,3.000000,2020-06-16,NaN,Supplier B,Top selling,NaN
153,Camera,Clothing,4959,147,104,Brand B,0.13,3.000000,2021-04-03,NaN,NaN,Top selling,USA
300,Smartwatch,Clothing,4851,120,77,Brand C,0.23,2.000000,2023-12-07,2.0,Supplier B,Good quality product,USA
249,Laptop,Clothing,4588,416,71,Brand D,0.08,3.000000,2024-04-21,2.0,Supplier B,Good quality product,NaN
163,Camera,Clothing,4499,176,176,Brand E,0.27,3.000000,2021-03-28,3.0,Supplier C,NaN,USA
140,Keyboard,Electronics,4833,115,156,Brand A,0.11,1.000000,2023-11-18,NaN,Supplier B,Affordable price,China
231,Keyboard,Electronics,4688,221,127,Brand B,0.22,2.000000,2022-05-17,5.0,Supplier C,Good quality product,NaN
379,Phone,Electronics,4401,150,283,Brand C,0.05,2.000000,2022-06-05,NaN,Supplier A,Top selling,India
215,Camera,Electronics,4833,306,193,Brand D,0.15,5.000000,2023-02-07,NaN,NaN,Affordable price,Germany
470,Monitor,Electronics,4420,121,270,Brand E,0.14,2.000000,2023-01-02,2.0,NaN,Top selling,China
390,Phone,Furniture,4378,425,161,Brand A,0.25,5.000000,2024-08-08,2.0,Supplier B,Top selling,Germany
495,Charger,Furniture,2980,386,137,Brand B,0.08,2.993921,2022-08-15,3.0,Supplier C,Top selling,India
280,Monitor,Furniture,4775,275,296,Brand C,0.27,4.000000,2024-07-22,1.0,Supplier C,Good quality product,USA
185,Monitor,Furniture,4945,47,297,Brand D,0.33,1.000000,2021-08-07,1.0,NaN,Best in class,USA
115,Phone,Furniture,4875,237,21,Brand E,0.09,5.000000,2021-05-07,2.0,NaN,Affordable price,China
207,Monitor,Home Appliances,4999,311,149,Brand A,0.29,3.000000,2024-05-01,2.0,NaN,Affordable price,Germany
193,Charger,Home Appliances,4920,492,202,Brand B,0.24,2.000000,2021-10-29,2.0,NaN,Top selling,Germany
394,Camera,Home Appliances,4989,470,71,Brand C,0.20,2.993921,2022-06-17,2.0,Supplier B,Best in class,NaN
358,Monitor,Home Appliances,4958,438,57,Brand D,0.14,3.000000,2023-08-01,5.0,Supplier A,NaN,China
103,Charger,Home Appliances,4942,197,106,Brand E,0.07,2.993921,2024-11-11,2.0,Supplier C,Top selling,China

In [ ]:
df.groupby('Category')['Stock'].count() # total number of products in each category

Category
Accessories        78
Clothing           79
Electronics        79
Furniture          74
Home Appliances    90
Name: Stock, dtype: int64

In [ ]:
df.groupby('Category')['Price'].mean() # average price of product in each category

Category
Accessories        2438.512821
Clothing           2392.848101
Electronics        2413.531646
Furniture          2825.864865
Home Appliances    2819.666667
Name: Price, dtype: float64

In [86]:
# total stock
df.groupby('Category')['Stock'].sum().sum()

np.int64(105121)

In [87]:
# in terms of brand, total number of products
df.groupby('Brand')['Stock'].count()

Brand
Brand A    70
Brand B    86
Brand C    69
Brand D    91
Brand E    84
Name: Stock, dtype: int64

In [ ]:
# maximum priced product for each brand
df.groupby('Brand')['Price'].max()

Brand
Brand A    4999
Brand B    4959
Brand C    4989
Brand D    4958
Brand E    4942
Name: Price, dtype: int64

In [89]:
# minimum stock
df.groupby('Brand')['Stock'].min()

Brand
Brand A    11
Brand B     4
Brand C     6
Brand D     3
Brand E     2
Name: Stock, dtype: int64

In [ ]:
# total sales computation
df['Total Sales'] = df['Price'] * df['Stock']
df

,Product Name,Category,Price,Stock,Sales,Brand,Discount,Rating,Launch Date,Warranty Period (Years),Supplier,Product Description,Manufacture Country,Total Sales
Product ID,,,,,,,,,,,,,,
101,Monitor,Accessories,1156,482,29,Brand C,0.21,2.993921,2020-07-20,2.0,NaN,Best in class,India,557192
102,Headphones,Clothing,289,305,45,Brand E,0.06,3.000000,2022-01-16,1.0,Supplier B,Best in class,China,88145
103,Charger,Home Appliances,4942,197,106,Brand E,0.07,2.993921,2024-11-11,2.0,Supplier C,Top selling,China,973574
104,Laptop,Clothing,1359,328,259,Brand E,0.13,2.993921,2022-12-18,NaN,NaN,Affordable price,India,445752
105,Camera,Electronics,4382,204,166,Brand E,0.34,2.993921,2024-08-26,3.0,Supplier B,Best in class,China,893928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Tablet,Accessories,829,285,197,Brand E,0.22,5.000000,2020-03-04,5.0,NaN,Good quality product,India,236265
497,Keyboard,Home Appliances,4762,244,149,Brand E,0.34,2.000000,2024-07-01,2.0,NaN,Top selling,China,1161928
498,Monitor,Accessories,478,413,88,Brand C,0.30,4.000000,2023-04-13,3.0,Supplier A,NaN,China,197414
499,Charger,Furniture,3005,302,226,Brand E,0.14,2.000000,2020-06-15,2.0,Supplier B,NaN,India,907510
500,Monitor,Electronics,3403,255,97,Brand B,0.18,3.000000,2021-01-13,1.0,Supplier B,Top selling,Germany,867765

In [ ]:
# total sales by brand
totalSalesByBrand = df.groupby('Brand')['Total Sales'].sum()
totalSalesByBrand

Brand
Brand A    50344685
Brand B    55862014
Brand C    41254053
Brand D    68676128
Brand E    55661866
Name: Total Sales, dtype: int64

In [ ]:
# brand with highest total sales
brand = totalSalesByBrand.idxmax()
value = max(totalSalesByBrand)
print(brand, '--->', value)

Brand D ---> 68676128

In [ ]:
# unique brands in each category
cat = df.groupby('Category')['Brand'].describe()
cat

                count unique      top freq
Category
Accessories        78      5  Brand B   22
Clothing           79      5  Brand B   21
Electronics        79      5  Brand A   18
Furniture          74      5  Brand E   23
Home Appliances    90      5  Brand B   22

In [ ]:
# highest average price 
catByPrice = df.groupby('Category')['Price'].mean()
sortedHighest = catByPrice.sort_values(ascending=False)

sortedHighest.head(3)

Category
Furniture          2825.864865
Home Appliances    2819.666667
Accessories        2438.512821
Name: Price, dtype: float64