deepdive

In [1]:
# import
import numpy as np
import pandas as pd

In [ ]:
# loading dataset

data = pd.read_csv('../datasets/aq2.csv')
df = pd.DataFrame(data)
df

FileNotFoundError: [Errno 2] No such file or directory: '..datasets/aq2.csv'

In [70]:
# viewing data

df.head() # first 5 rows
df.tail() # last 5 rows

df.head(10) #first 10 rows

              datetime  station_antwerp  station_paris  station_london
0  2019-05-07 02:00:00              NaN            NaN            23.0
1  2019-05-07 03:00:00             50.5           25.0            19.0
2  2019-05-07 04:00:00             45.0           27.7            19.0
3  2019-05-07 05:00:00              NaN           50.4            16.0
4  2019-05-07 06:00:00              NaN           61.9             NaN
5  2019-05-07 07:00:00              NaN           72.4            26.0
6  2019-05-07 08:00:00              NaN           77.7            32.0
7  2019-05-07 09:00:00              NaN           67.9            32.0
8  2019-05-07 10:00:00              NaN           56.0            28.0
9  2019-05-07 11:00:00              NaN           34.5            21.0

In [71]:
# dataframe.assign()

df.assign(randomId=df['station_antwerp'] * df['station_paris'])
df.assign(randomId=np.random.randint(1001, 9999, size=df.shape[0]))
# df.shape[0]

,datetime,station_antwerp,station_paris,station_london,randomId
0,2019-05-07 02:00:00,NaN,NaN,23.0,3326
1,2019-05-07 03:00:00,50.5,25.0,19.0,5793
2,2019-05-07 04:00:00,45.0,27.7,19.0,2068
3,2019-05-07 05:00:00,NaN,50.4,16.0,4310
4,2019-05-07 06:00:00,NaN,61.9,NaN,6823
...,...,...,...,...,...
1030,2019-06-20 22:00:00,NaN,21.4,NaN,7888
1031,2019-06-20 23:00:00,NaN,24.9,NaN,8567
1032,2019-06-21 00:00:00,NaN,26.5,NaN,7317
1033,2019-06-21 01:00:00,NaN,21.8,NaN,6025
1034,2019-06-21 02:00:00,NaN,20.0,NaN,9163

In [72]:
df.pop('station_antwerp')

0        NaN
1       50.5
2       45.0
3        NaN
4        NaN
        ...
1030     NaN
1031     NaN
1032     NaN
1033     NaN
1034     NaN
Name: station_antwerp, Length: 1035, dtype: float64

In [73]:
df

                 datetime  station_paris  station_london
0     2019-05-07 02:00:00            NaN            23.0
1     2019-05-07 03:00:00           25.0            19.0
2     2019-05-07 04:00:00           27.7            19.0
3     2019-05-07 05:00:00           50.4            16.0
4     2019-05-07 06:00:00           61.9             NaN
...                   ...            ...             ...
1030  2019-06-20 22:00:00           21.4             NaN
1031  2019-06-20 23:00:00           24.9             NaN
1032  2019-06-21 00:00:00           26.5             NaN
1033  2019-06-21 01:00:00           21.8             NaN
1034  2019-06-21 02:00:00           20.0             NaN

[1035 rows x 3 columns]

In [109]:
df['station_paris'] # selects column

df.loc[5] # prints rows by row label / integer position of the row

df[2:34] # slices rows based on specified; returns a data frame

df[~df['station_paris'].isna()]

                 datetime  station_paris  station_london
1     2019-05-07 03:00:00           25.0            19.0
2     2019-05-07 04:00:00           27.7            19.0
3     2019-05-07 05:00:00           50.4            16.0
4     2019-05-07 06:00:00           61.9             NaN
5     2019-05-07 07:00:00           72.4            26.0
...                   ...            ...             ...
1030  2019-06-20 22:00:00           21.4             NaN
1031  2019-06-20 23:00:00           24.9             NaN
1032  2019-06-21 00:00:00           26.5             NaN
1033  2019-06-21 01:00:00           21.8             NaN
1034  2019-06-21 02:00:00           20.0             NaN

[1004 rows x 3 columns]

In [125]:
df3 = pd.DataFrame(np.random.randn(10, 4), columns=["A", "B", "C", "D"])

df2 = pd.DataFrame(np.random.randn(7, 3), columns=["A", "B", "C"])

df3 + df2

          A         B         C   D
0 -1.071769 -0.082474 -0.850755 NaN
1 -0.901807  0.361173 -2.397108 NaN
2  0.048986 -1.219147  0.876132 NaN
3 -0.044075 -2.924617 -2.521060 NaN
4 -0.334143  0.416912  0.316464 NaN
5 -0.788121  1.255976 -0.695993 NaN
6 -1.596907  0.815074  0.017958 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Columns: 4 entries, A to D
dtypes: float64(4)
memory usage: 452.0 bytes

In [138]:
df3.apply(lambda x: np.round(x, 4))

df3.pipe(lambda y: np.round(np.exp(y), 4))

df3.agg(np.average)

A    0.252190
B   -0.718227
C    0.171518
D   -0.031993
dtype: float64